"""
TaxEaseLK — Re-export from root database.py for backward compatibility and clean API imports.
"""

from database import (
    supabase,
    supabase_anon,
    SUPABASE_URL,
    SUPABASE_SERVICE_KEY,
    SUPABASE_ANON_KEY,
    DATABASE_URL,
    engine,
    SessionLocal,
    Base,
    get_db,
    create_tables,
    
    # Enums
    AuditorStatusEnum,
    IssueSeverityEnum,
    IssueStatusEnum,
    SubmissionStatusEnum,
    InvitationStatusEnum,
    ReviewIssueStatusEnum,
    UserRoleEnum,
    UserStatusEnum,
    CITStatusEnum,
    ReviewStatusEnum,
    RiskLevelEnum,
    AuditUserTypeEnum,
    
    # Models
    Business,
    FinancialYear,
    Document,
    ExtractedValue,
    DocumentHistory,
    ActionRequired,
    Notification,
    AuditorSubmission,
    SubmissionHistory,
    AuditorInvitation,
    AuditorReview,
    ReviewIssue,
    ReviewIssueAttachment,
    CompanyUser,
    SecuritySetting,
    UserSession,
    NotificationPreference,
    AuditLog
)

__all__ = [
    "supabase",
    "supabase_anon",
    "SUPABASE_URL",
    "SUPABASE_SERVICE_KEY",
    "SUPABASE_ANON_KEY",
    "DATABASE_URL",
    "engine",
    "SessionLocal",
    "Base",
    "get_db",
    "create_tables",
    "AuditorStatusEnum",
    "IssueSeverityEnum",
    "IssueStatusEnum",
    "SubmissionStatusEnum",
    "InvitationStatusEnum",
    "ReviewIssueStatusEnum",
    "UserRoleEnum",
    "UserStatusEnum",
    "CITStatusEnum",
    "ReviewStatusEnum",
    "RiskLevelEnum",
    "AuditUserTypeEnum",
    "Business",
    "FinancialYear",
    "Document",
    "ExtractedValue",
    "DocumentHistory",
    "ActionRequired",
    "Notification",
    "AuditorSubmission",
    "SubmissionHistory",
    "AuditorInvitation",
    "AuditorReview",
    "ReviewIssue",
    "ReviewIssueAttachment",
    "CompanyUser",
    "SecuritySetting",
    "UserSession",
    "NotificationPreference",
    "AuditLog",
]
